//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB)
//Reference Implementation, v2.2.4-2
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the
//source schema.
// Generated on: 2014.04.25 at 07:45:04 PM CDT
//

package edu.utdallas.old;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;

/**
 *
 * @author Sean SpeedType, an enumerated value for use with AnimationEffectType.
 *         Preferred method of setting in code is with SpeedType.FAST,
 *         SpeedType.MEDIUM, etc, rather than using the local variable name.
 *         NOTE: due to overlap with the Speed class, this class is being
 *         removed to correct the redundancy. Please change references to
 *         SpeedType to Speed accordingly.
 *
 */
@XmlType(name = "SpeedType")
@XmlEnum
public enum SpeedType {

	/**
	 * Fast speed.
	 */
	FAST,
	/**
	 * Medium speed.
	 */
	MEDIUM,
	/**
	 * Slow speed.
	 */
	SLOW;

	/**
	 *
	 * @return {@link String}
	 */
	public String value() {
		return name();
	}

	/**
	 *
	 * @param v
	 *            {@link String}
	 * @return {@link SpeedType}
	 */
	public static SpeedType fromValue(final String v) {
		return valueOf(v);
	}

}
